import os
import pandas as pd
from django.core.management.base import BaseCommand
from django.conf import settings
from forecasting.models import LoadReading


class Command(BaseCommand):
    help = 'Seeds real_load_data_hourly.csv (generated by train_forecast_model) into LoadReading table'

    def handle(self, *args, **kwargs):
        csv_path = os.path.join(
            settings.BASE_DIR, 'forecasting', 'ml', 'data', 'real_load_data_hourly.csv'
        )

        if not os.path.exists(csv_path):
            self.stderr.write(
                "real_load_data_hourly.csv not found. "
                "Run 'py manage.py train_forecast_model' first."
            )
            return

        self.stdout.write("Reading CSV...")
        df = pd.read_csv(csv_path)
        df['datetime'] = pd.to_datetime(df['datetime'])

        # Clear old seeded data
        deleted, _ = LoadReading.objects.all().delete()
        self.stdout.write(f"Cleared {deleted} old records.")

        batch = [
            LoadReading(
                datetime    = row['datetime'],
                load_kwh    = row['load_kwh'],
                temperature = 0.0,              # not available in LCL data
                hour        = int(row['hour']),
                day_of_week = int(row['day_of_week']),
                is_weekend  = bool(row['is_weekend']),
                month       = int(row['month']),
            )
            for _, row in df.iterrows()
        ]

        LoadReading.objects.bulk_create(batch, batch_size=500)
        self.stdout.write(self.style.SUCCESS(
            f"✓ Seeded {len(batch)} real LCL records into LoadReading table."
        ))