# Generated by Django 6.0.5 on 2026-05-20 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('apartment', 'Apartment')], default='residential', max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('govt_property_id', models.CharField(blank=True, help_text='Government-issued property/house ID', max_length=100)),
                ('utility_account_no', models.CharField(blank=True, help_text='Electricity utility account number', max_length=100)),
                ('consumer_no', models.CharField(blank=True, help_text='NEA or local utility consumer number', max_length=100)),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=50)),
                ('tariff_plan', models.CharField(choices=[('standard', 'Standard Fixed Rate'), ('tou', 'Time of Use'), ('prepaid', 'Prepaid'), ('net_metering', 'Net Metering (Solar)')], default='standard', max_length=20)),
                ('peak_rate', models.FloatField(default=1.257, help_text='NPR per kWh during peak')),
                ('flat_rate', models.FloatField(default=0.787, help_text='NPR per kWh during flat')),
                ('valley_rate', models.FloatField(default=0.299, help_text='NPR per kWh during valley')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(help_text='Device MAC address e.g. AA:BB:CC:DD:EE:FF', max_length=17, unique=True)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(help_text='e.g. "Main meter", "Solar panel meter"', max_length=100)),
                ('meter_type', models.CharField(choices=[('main', 'Main Grid Meter'), ('sub', 'Sub Meter'), ('solar', 'Solar Generation Meter'), ('ev', 'EV Charging Meter'), ('industrial', 'Industrial Meter')], default='main', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('rated_capacity_kw', models.FloatField(blank=True, help_text='Max rated capacity in kW', null=True)),
                ('phase', models.CharField(choices=[('single', 'Single Phase'), ('three', 'Three Phase')], default='single', max_length=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='properties.property')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_usage', 'High Usage'), ('outage', 'Power Outage'), ('tamper', 'Tampering Detected'), ('peak', 'Peak Demand Warning'), ('low_voltage', 'Low Voltage')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='properties.smartmeter')),
            ],
        ),
        migrations.CreateModel(
            name='HomeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('readonly', 'Read Only')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_memberships', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('consumption_kwh', models.FloatField()),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('current_amps', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, null=True)),
                ('frequency_hz', models.FloatField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='properties.smartmeter')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('meter', 'timestamp')},
            },
        ),
    ]
