# Generated by Django 6.0.5 on 2026-05-18 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_kw', models.FloatField()),
                ('duration_hrs', models.IntegerField()),
                ('start_window', models.IntegerField()),
                ('end_window', models.IntegerField()),
                ('appliance_class', models.CharField(choices=[('IL', 'Inflexible'), ('SL', 'Shiftable'), ('AL', 'Adjustable')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_cost', models.FloatField()),
                ('optimized_cost', models.FloatField()),
                ('cost_saving', models.FloatField()),
                ('peak_reduction', models.FloatField()),
                ('schedule_json', models.JSONField()),
                ('hourly_json', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
