# Generated by Django 6.0.5 on 2026-05-20 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_kw', models.FloatField()),
                ('duration_hrs', models.IntegerField()),
                ('start_window', models.IntegerField()),
                ('end_window', models.IntegerField()),
                ('appliance_class', models.CharField(choices=[('IL', 'Inflexible'), ('SL', 'Shiftable'), ('AL', 'Adjustable')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeakEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('hour', models.IntegerField()),
                ('load_kw', models.FloatField()),
                ('threshold_kw', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peak_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('reporting_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('original_cost_gbp', models.FloatField()),
                ('optimized_cost_gbp', models.FloatField()),
                ('cost_saving_gbp', models.FloatField()),
                ('carbon_reduced_kg', models.FloatField()),
                ('has_risk', models.BooleanField(default=False)),
                ('risk_events', models.IntegerField(default=0)),
                ('peak_threshold_kw', models.FloatField()),
                ('user_peak_load_kw', models.FloatField()),
                ('congratulations_message', models.TextField(blank=True)),
                ('environmental_message', models.TextField(blank=True)),
                ('notification_text', models.TextField(blank=True)),
                ('hourly_json', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('mac_address', 'reporting_date')},
            },
        ),
    ]
