"""
Django settings for smart_load_api project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
from django.utils.translation import gettext_lazy as _

# This will search for a .env file in the current directory or parent directories
load_dotenv()


SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Apps — use full AppConfig path for any app that has signals
    'accounts.apps.AccountsConfig',
    'data_ingestion',
    'forecasting',
    'demand_response.apps.DemandResponseConfig',
    'analytics',
    'properties',
    'notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Allow React dev server
FRONTEND_URL = os.getenv("FRONTEND_URL", default="http://localhost:5173")
CORS_ALLOWED_ORIGINS = [FRONTEND_URL]

# JWT authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


ROOT_URLCONF = 'smart_load_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smart_load_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



AUTH_USER_MODEL = 'accounts.CustomUser'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':     timedelta(minutes=60),  # 1 hour — reasonable
    'REFRESH_TOKEN_LIFETIME':    timedelta(days=30),     # 30 days — user stays logged in
    'ROTATE_REFRESH_TOKENS':     True,    # each refresh gives a new refresh token
    'BLACKLIST_AFTER_ROTATION':  True,    # old refresh token is invalidated
}

PASSWORD_RESET_TIMEOUT_MINUTES = 15  # for OTP expiration check in PasswordResetRequest model


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"          # or your SMTP provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")  # your email address
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # app password, not your login password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




UNFOLD = {

    # ─────────────────────────────────────────────
    # SITE
    # ─────────────────────────────────────────────
    "SITE_TITLE": "Smart Load DR",
    "SITE_HEADER": "Smart Load DR Admin",
    "SITE_SYMBOL": "bolt",
    

    # ─────────────────────────────────────────────
    # SIDEBAR
    # ─────────────────────────────────────────────
    "SIDEBAR": {
        "show_search": True,

        "navigation": [

            # DASHBOARD
            {
                "title": "Dashboard",
                "separator": True,
                "items": [
                    {
                        "title": "Analytics Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/dashboard/",
                    },
                ],
            },

            # ACCOUNTS
            {
                "title": "Accounts",
                "separator": True,
                "items": [
                    {
                        "title": "Users",
                        "icon": "people",
                        "link": "/admin/accounts/customuser/",
                    },
                    {
                        "title": "Groups",
                        "icon": "group_work",
                        "link": "/admin/auth/group/",
                    },
                ],
            },

            # PROPERTIES
            {
                "title": "Properties",
                "separator": True,
                "items": [
                    {
                        "title": "Properties",
                        "icon": "home",
                        "link": "/admin/properties/property/",
                    },
                    {
                        "title": "Smart Meters",
                        "icon": "speed",
                        "link": "/admin/properties/smartmeter/",
                    },
                    {
                        "title": "Home Members",
                        "icon": "family_restroom",
                        "link": "/admin/properties/homemember/",
                    },
                    {
                        "title": "Energy Readings",
                        "icon": "electric_bolt",
                        "link": "/admin/properties/energyreading/",
                    },
                ],
            },

            # FORECASTING
            {
                "title": "Forecasting",
                "separator": True,
                "items": [
                    {
                        "title": "Load Readings",
                        "icon": "query_stats",
                        "link": "/admin/forecasting/loadreading/",
                    },
                    {
                        "title": "Forecast Results",
                        "icon": "monitoring",
                        "link": "/admin/forecasting/forecastresult/",
                    },
                ],
            },

            # DEMAND RESPONSE
            {
                "title": "Demand Response",
                "separator": True,
                "items": [
                    {
                        "title": "Appliance Profiles",
                        "icon": "devices",
                        "link": "/admin/demand_response/applianceprofile/",
                    },
                    {
                        "title": "DR Results",
                        "icon": "savings",
                        "link": "/admin/demand_response/drresult/",
                    },
                    {
                        "title": "Peak Events",
                        "icon": "warning",
                        "link": "/admin/demand_response/peakevent/",
                    },
                ],
            },

            # ANALYTICS
            {
                "title": "Analytics",
                "separator": True,
                "items": [
                    {
                        "title": "Reports",
                        "icon": "analytics",
                        "link": "/admin/analytics/",
                    },
                ],
            },

            # NOTIFICATIONS
            {
                "title": "Notifications",
                "separator": True,
                "items": [
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": "/admin/notifications/",
                    },
                ],
            },
        ],
    },
}