# Generated by Django 6.0.5 on 2026-05-17 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('target_hour', models.DateTimeField()),
                ('predicted_kw', models.FloatField()),
                ('is_peak', models.BooleanField(default=False)),
                ('model_used', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_hour'],
            },
        ),
        migrations.CreateModel(
            name='LoadReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True)),
                ('load_kw', models.FloatField()),
                ('temperature', models.FloatField()),
                ('hour', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('is_weekend', models.BooleanField()),
                ('month', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
