# Generated by Django 6.0.5 on 2026-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastresult',
            old_name='predicted_kw',
            new_name='predicted_kwh',
        ),
        migrations.RenameField(
            model_name='loadreading',
            old_name='load_kw',
            new_name='load_kwh',
        ),
        migrations.AlterField(
            model_name='forecastresult',
            name='model_used',
            field=models.CharField(default='Random Forest', max_length=50),
        ),
        migrations.AlterField(
            model_name='loadreading',
            name='temperature',
            field=models.FloatField(default=0),
        ),
    ]
